
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 37;
  public static final int INCREMENT = 34;
  public static final int CHAR = 24;
  public static final int CHAR_LITERAL = 36;
  public static final int GE = 19;
  public static final int LPAREN = 2;
  public static final int SEMI = 7;
  public static final int INT = 25;
  public static final int DECREMENT = 35;
  public static final int FOR = 33;
  public static final int STAR = 10;
  public static final int RPAREN = 3;
  public static final int NOT = 12;
  public static final int AND = 13;
  public static final int LT = 18;
  public static final int OR = 14;
  public static final int COMMA = 6;
  public static final int DIV = 11;
  public static final int ASSIGN = 21;
  public static final int IF = 29;
  public static final int LE = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 27;
  public static final int RETURN = 32;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int ADD = 8;
  public static final int EQ = 15;
  public static final int ERROR = 40;
  public static final int COLON = 41;
  public static final int LBRACE = 4;
  public static final int ELSE = 30;
  public static final int WHILE = 31;
  public static final int RBRACE = 5;
  public static final int NE = 16;
  public static final int STRING = 26;
  public static final int FALSE = 22;
  public static final int GT = 20;
  public static final int SUB = 9;
  public static final int PRINT = 28;
  public static final int INT_LITERAL = 38;
  public static final int IDENTIFIER = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "ADD",
  "SUB",
  "STAR",
  "DIV",
  "NOT",
  "AND",
  "OR",
  "EQ",
  "NE",
  "LE",
  "LT",
  "GE",
  "GT",
  "ASSIGN",
  "FALSE",
  "TRUE",
  "CHAR",
  "INT",
  "STRING",
  "BOOLEAN",
  "PRINT",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "FOR",
  "INCREMENT",
  "DECREMENT",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "INT_LITERAL",
  "IDENTIFIER",
  "ERROR",
  "COLON"
  };
}

